# Generated by Django 5.1 on 2024-09-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_rename_customuser_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomUser',
        ),
    ]
