# Generated by Django 5.1 on 2024-09-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_customer_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email',
            new_name='UserEmail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='UserAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
