# Generated by Django 5.1 on 2024-09-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_email_customuser_useremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='UserAddress',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='UserEmail',
            new_name='user_email',
        ),
    ]
