# Generated by Django 5.1 on 2024-09-04 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_rename_image_link_author_author_image'),
        ('CustomerFollow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerfollow',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='customerfollow',
            old_name='user',
            new_name='user_email',
        ),
        migrations.AlterUniqueTogether(
            name='customerfollow',
            unique_together={('user_email', 'author_name')},
        ),
    ]
