# Generated by Django 5.1 on 2024-09-04 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_index', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=12, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.customerorder')),
            ],
            options={
                'unique_together': {('order', 'book')},
            },
        ),
    ]
