# Generated by Django 5.1 on 2024-09-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image_link',
            new_name='author_image',
        ),
    ]
