# Generated by Django 5.1 on 2024-09-04 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_rename_author_book_author_name_and_more'),
        ('CustomerCartBook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercartbook',
            old_name='book',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='customercartbook',
            old_name='user',
            new_name='user_email',
        ),
        migrations.AlterUniqueTogether(
            name='customercartbook',
            unique_together={('user_email', 'book_name')},
        ),
    ]
