# Generated by Django 5.1 on 2024-09-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerCartBook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercartbook',
            name='num_books',
            field=models.IntegerField(default=0),
        ),
    ]
