# Generated by Django 5.1 on 2024-09-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='book_description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='book_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='language',
            new_name='book_language',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='page_count',
            new_name='book_page',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='weight',
            new_name='book_weight',
        ),
    ]
