# Generated by Django 5.1 on 2024-09-07 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
        ('Order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.customerorder'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order_index', 'book_name')},
        ),
    ]
